apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z8n109p95-python-gitops
  description: This is GitOps manifest for z8n109p95-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=z8n109p95-python
    backstage.io/kubernetes-id: z8n109p95-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: z8n109p95-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z8n109p95-python
